### PR TITLE
Create BitOK.json

### PR DESCRIPTION
**Pull request by BitOKorg**
Signed-off-by: BitOK <119669726+BitOKorg@users.noreply.github.com>

### CODE REVIEW

**Comment by itsenpai** [comment]
> 

Hi! yes.

**Comment by cdc-william** [comment]
Hi @BitOKorg , I was unable to find any Cronos related material in your project website and [API Guides](https://bitok.org/apiguides). I cannot add it if it is not related to the Cronos ecosystem.

**Comment by BitOKorg** [comment]
Hi @cdc-william , Dear William,

Thank you for getting back to us. As you can see from the screenshot attched, Cronos blockchain is supported on BitOK and enables Cronos' users to get information about portfolio PnL, manage accounting documents and taxes.

Please check for yourself https://app.bitok.org/login
photo_2022-12-30_15-59-38

Kind regards

**Review by cdc-william — APPROVED** [review]

**Comment by cdc-william** [comment]
Cool, great to know! I also updated a bit on the file you submitted.

**Comment by cdc-william** [comment]
Thanks for the PR! We just added BitOK to our [Ecosystem page](https://cronos.org/ecosystem)! 🥳

**Pull request merged**
